RunMode: debug
Addr: :8080                  # HTTP绑定端口

# MySQL 数据库相关配置
Database:
  Host: 127.0.0.1:3306 # MySQL 机器 ip 和端口，默认 127.0.0.1:3306
  Username: root # MySQL 用户名(建议授权最小权限集)
  Password:  # MySQL 用户密码
  DatabaseName: goserver # goserver 系统所用的数据库名
  MaxIdleConns: 100 # MySQL 最大空闲连接数，默认 100
  MaxOpenConns: 100 # MySQL 最大打开的连接数，默认 100
  ConnMaxLifetime: 10s # 空闲连接最大存活时间，默认 10s
  LoggerLevel: 4 # GORM log level, 1: silent, 2:error, 3:warn, 4:info